### PR TITLE
Features for release 7.0

### PR DESCRIPTION
**Pull request by JinmingHu-MSFT**
Features:

* GetShareStats
* Blob snapshot SAS
* OAuth 2.0
* CRC64
* File SMB properties

Misc:
* Fix a typo in API `azure::storage::cloud_file_share::download_share_usage_async`
* Fix a typo in API `azure::storage::cloud_queue_message::next_visible_time`
* Upgrade UnitTest++ to latest on Windows
* Raise minimum required GCC to 5.1
* Set up CI with Azure Pipelines

### CODE REVIEW

**Comment by JinmingHu-MSFT** [comment]
> It seems that the guideline for installing Unittest++ on Windows is missing in Readme.md, can you add it to avoid confusion?

Since there will be another commit updating all those version strings from 6.1.0 to 7.0.0, and latest UnitTest++ for Windows is only supported from 7.0.0, I'm thinking of adding the guideline in that commit. How do you think?

**Comment by katmsft** [comment]
> > It seems that the guideline for installing Unittest++ on Windows is missing in Readme.md, can you add it to avoid confusion?
> 
> Since there will be another commit updating all those version strings from 6.1.0 to 7.0.0, and latest UnitTest++ for Windows is only supported from 7.0.0, I'm thinking of adding the guideline in that commit. How do you think?

I think it would be great :).

**Comment by JinmingHu-MSFT** [comment]
@katmsft hey, I'm done with this. Check this out [11aad25](https://github.com/Azure/azure-storage-cpp/commit/11aad2599904fa8fc51da2dd163fbf44c77b1772)

**Comment by JinmingHu-MSFT** [comment]
> What about the change made in file service, e.g. `get_share_stats`?

It's in commit [11c6bdb](https://github.com/Azure/azure-storage-cpp/pull/290/commits/11c6bdbc8219439dd8717c3a6e2faaa29372ad1c).

**Pull request merged**
