### PR TITLE
Export methods to set/get the ambient pplx scheduler

### PR DESCRIPTION
**Pull request by chakrab-msft**
Enable callers of azure storage apis to plugin a custom scheduler for ppl tasks.

### CODE REVIEW

**Comment by achie-liang** [comment]
Hi @chakrab-msft , I didn't get a chance to see whether same interface exist for pplx on Linux yet.
Did you verify the build on Linux?

**Comment by achie-liang** [comment]
Based on [cpprest document](https://microsoft.github.io/cpprestsdk/namespacepplx.html), pplx::get_ambient_scheduler() return value type instead of reference type.
Please fix this.

**Comment by chakrab-msft** [comment]
I haven't verified on Linux; I have sent out another [PR ](https://github.com/Microsoft/cpprestsdk/pull/670/files)to the cpprestsdk folks to make a similar change to export the set_cpprestsdk_ambient_scheduler method.

**Comment by katmsft** [comment]
Hi @chakrab-msft , any chance that you could also add test code to your added interfaces?

**Comment by chakrab-msft** [comment]
Added a unit test that sets the delayed scheduler and verifies that retry happened. Can you please double check this passes? Thanks.

**Comment by katmsft** [comment]
Build/UT finished on Windows and Linux, no problems found.

**Pull request merged**
