### PR TITLE
Added tests to verify lease support in set blob tier

### PR DESCRIPTION
**Pull request by katmsft**

### CODE REVIEW

**Comment by vinjiang** [comment]
Can one of the admins verify this patch?

**Comment by JasonYang-MSFT** [comment]
add to whitelist

**Comment by vinjiang** [comment]
Failed

**Comment by JasonYang-MSFT** [comment]
retest this please

**Comment by vinjiang** [comment]
Failed

**Comment by JasonYang-MSFT** [comment]
retest this please

**Comment by vinjiang** [comment]
Failed

**Comment by JasonYang-MSFT** [comment]
retest this please

**Comment by vinjiang** [comment]
Failed

**Comment by vinjiang** [comment]
Build or test failed on Ubuntu 16.04!

**Comment by vinjiang** [comment]
Failed

**Comment by vinjiang** [comment]
Build or test failed on Ubuntu 16.04!

**Comment by vinjiang** [comment]
Failed

**Comment by vinjiang** [comment]
Build or test failed on Ubuntu 16.04!

**Comment by vinjiang** [comment]
Failed

**Comment by vinjiang** [comment]
Build or test failed on Ubuntu 16.04!

**Comment by vinjiang** [comment]
Failed

**Comment by vinjiang** [comment]
Build or test failed on Ubuntu 16.04!

**Comment by vinjiang** [comment]
Failed

**Comment by vinjiang** [comment]
Failed

**Comment by JasonYang-MSFT** [comment]
retest this please

**Comment by vinjiang** [comment]
Failed

**Comment by JasonYang-MSFT** [comment]
retest this please

**Comment by vinjiang** [comment]
Failed

**Comment by vinjiang** [comment]
Failed

**Comment by katmsft** [comment]
retest this please

**Comment by vinjiang** [comment]
Failed

**Comment by katmsft** [comment]
retest this please

**Comment by vinjiang** [comment]
Failed

**Comment by vinjiang** [comment]
Failed

**Comment by katmsft** [comment]
retest this please

**Comment by vinjiang** [comment]
Failed

**Comment by katmsft** [comment]
retest this please

**Comment by vinjiang** [comment]
Failed

**Comment by vinjiang** [comment]
Failed

**Comment by katmsft** [comment]
retest this please

**Comment by vinjiang** [comment]
Failed

**Comment by vinjiang** [comment]
Failed

**Comment by katmsft** [comment]
retest this please

**Comment by vinjiang** [comment]
Failed

**Comment by katmsft** [comment]
retest this please

**Comment by katmsft** [comment]
retest this please

**Comment by vinjiang** [comment]
Failed

**Pull request merged**
