### PR TITLE
Fix broken links in README

### PR DESCRIPTION
**Pull request by chwarr**
Now, directly link to http://azure.microsoft.com/ instead of relative linking.

### CODE REVIEW

**Comment by chwarr** [comment]
:point_left: Poke. Anyone looking at these pull requests?

**Comment by chwarr** [comment]
Tickle. I'd like to come to closure on this PR, please, even if it is rejected.

**Comment by hanzhumsft** [comment]
@chwarr Please re-create the pull request against our new dev branch. This branch is for community contribution starting from v2.3 release.

**Comment by chwarr** [comment]
#53, which is against the dev branch, replaces this one.

**Pull request closed without merging**
