### PR TITLE
Added ABI Compatibility for OpenSSL

### PR DESCRIPTION
**Pull request by bjornefitte**

### CODE REVIEW

**Comment by katmsft** [comment]
Hi, can you elaborate on what this PR is for?

**Comment by jneuff** [comment]
See https://github.com/Azure/azure-storage-cpp/issues/131

**Comment by JasonYang-MSFT** [comment]
@bjornefitte Can you re-target to dev branch?

**Comment by howryu** [comment]
Do we know when this can be merged?

**Comment by JasonYang-MSFT** [comment]
We will merge it after 5.0.0 nuget release. We want to include this PR in 5.1.0 release.

**Comment by howryu** [comment]
Is there a target date for 5.1.0 release?

**Comment by JasonYang-MSFT** [comment]
It would be end of July.

**Comment by katmsft** [comment]
Please be aware that due to CPPRest's blocking issue [#804](https://github.com/Microsoft/cpprestsdk/issues/804), we are currently waiting CPPRest's newest release that fixes this issue to proceed.

**Pull request merged**
